const data = {
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 50,
      brand: 'Reebok',
      rating: 4.0,
      numReviews: 9,
      countStock: 10,
      description: 'A nice shirt cotton',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 40,
      brand: 'Rown Division',
      rating: 4.3,
      numReviews: 4,
      countStock: 12,
      description: 'A nice t-shirt cotton',
    },
    {
      name: 'Slimfit Shirt',
      slug: 'slimfit-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 40,
      brand: 'Shining Bright',
      rating: 4.9,
      numReviews: 9,
      countStock: 10,
      description: 'lorem ipsum dolor sit amet',
    },
    {
      name: 'Regular Pants',
      slug: 'regular-pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 110,
      brand: 'Culby',
      rating: 4.5,
      numReviews: 5,
      countStock: 2,
      description: 'lorem ipsum dolor sit amet',
    },
    {
      name: 'Casual Pants',
      slug: 'casual-pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 40,
      brand: 'Rown Division',
      rating: 4.3,
      numReviews: 4,
      countStock: 12,
      description: 'lorem ipsum dolor sit amet',
    },
    {
      name: 'Cargo Pants',
      slug: 'cargo-pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 40,
      brand: 'Army',
      rating: 4.9,
      numReviews: 7,
      countStock: 20,
      description: 'lorem ipsum dolor sit amet',
    },
  ],
}

export default data
